name: "Huu Thien Pham"
picture: "assets/img/picture.jpg"
bio: "Python/JavaScript Developer"
meta:
  lang: "en"
  description: "Python/JavaScript Developer"
  title: "Huu Thien Pham"
  author: "Huu Thien Pham"
  siteUrl: "https://huuthienp.github.io/linktree/"
links:
  - name: "Email"
    url: "mailto:hirehuuthienp@icloud.com"
  - name: "Github"
    url: "https://github.com/huuthienp"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/huuthienp/"
  - name: "Kaggle"
    url: "https://www.kaggle.com/huuthienp/code"
  # - name: ""
  #   url: ""
theme: "custom"
