name: Generate Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRIPT_NAME: 'generate_site.py'

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true

    - name: Sync Template Files
      env:
        REPO_URL: 'https://github.com/king-tri-ton/pythonpagelink.git'
      run: |
        git clone "$REPO_URL" temp-clone
        rsync -av --ignore-existing temp-clone .

    - run: uv pip install -r requirements.txt

    - run: python $SCRIPT_NAME
